// Serves /api/version (Ola/#225-B). Reads backend/src/version.json which
// is generated by scripts/build_version.sh at deploy time. If the file is
// missing or malformed, falls back to all-unknown so the endpoint never
// 500s — a missing version.json means the operator forgot to run the
// build script, which is a deploy-time bug surfaced by the unknown rev.

const fs = require('fs');
const path = require('path');

const VERSION_FILE = path.join(__dirname, '..', 'version.json');

const FALLBACK = Object.freeze({
  rev: 'unknown',
  sha: 'unknown',
  shaShort: 'unknown',
  branch: 'unknown',
  tag: null,
  builtAt: null,
});

async function getVersion(_req, res) {
  let v;
  try {
    const raw = fs.readFileSync(VERSION_FILE, 'utf8');
    const parsed = JSON.parse(raw);
    v = parsed && typeof parsed === 'object' ? parsed : { ...FALLBACK };
  } catch (_) {
    v = { ...FALLBACK };
  }
  return res.status(200).json({
    success: true,
    result: v,
    message: 'Devboard version',
  });
}

module.exports = getVersion;
module.exports.FALLBACK = FALLBACK;
